# Generated by Django 4.1.3 on 2022-11-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amigos',
            new_name='familiares',
        ),
    ]
